#!/bin/bash
rm -rf a
for iter in {1..100}
do
    echo "Iteration" ${iter} | tee -a a
    go test -run 3A 2>./log/a_${iter} |tee -a a
    if -q grep "history is not linearizable" a; then
        echo "Found not linearizable case"
        exit
    fi
done
